### ISSUE TITLE
CDATA , get data?! 

### ISSUE THREAD

**Issue by IssamJow** [wmfs/xml2csv#15]
Hello there, first of all i would like to thank you for this package, it's really helping me doing some work that i couldn't resolve in any other way.
I m new to Nodejs and have very little knowledge of XML, but i need to convert an XML to CSV, the only problem is, my xml has CDATA : ` <title><![CDATA[This is a title]]></title>`
i tried using .data on the headerMap,(see below) but i guess it isn't build that way

`promiseToGetFeed.then(fromResolve => {
    fs.writeFile(__dirname + "/items.xml", fromResolve, err => {});
    xml2csv({
        xmlPath: 'items.xml'
        , csvPath: 'items.csv'
        , rootXMLElement: 'item'
        , headerMap: [
        ['title'.data, 'title', 'string']
    ]
    }, function (err, info) {
        console.log(err, info)
            // Done!
    });`

Is there anyway that i get the data from the CData?! i would be really thankful for any answer from you guys. This is my first Issue ever :)

**Comment by thannes30** [comment]
Same issue here.
